CC = gcc
CFLAGS = -Wall -Wextra -O2
TARGET = hola
SRCS = main.c
OBJS = $(SRCS:.c=.o)

.PHONY: all run clean help rebuild

all: $(TARGET)

help:
	@echo "Objetivos disponibles:"
	@echo " make -> compila el programa"
	@echo " make run -> compila y ejecuta"
	@echo " make clean -> elimina archivos generados"
	@echo " make rebuild -> limpia y vuelve a compilar"

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)

rebuild: clean all